### PR TITLE
[feature] Add the ability to run commands per group of hosts.

### PR DESCRIPTION
**Pull request by DorianZaccaria**
The program will look for the environment attribute `MAX_HOSTS` which
defines the max number of hosts the command will run on in parallel.
If the attribute doesn't exist it will default to the total number of
hosts.

In addition, if the command fails on one or multiple hosts, the program
will exit with the error code 1 instead of 0 (default value).

I also added the binary name to a .gitignore file.

### CODE REVIEW

**Comment by jmoiron** [comment]
this could just be a command line flag, no?

**Comment by DorianZaccaria** [comment]
Thanks for the feedback.

**Comment by jmoiron** [comment]
I'll merge this, but I'm going to change the way it works so that max hosts is the max hosts done in parallel at any one time.  I think this makes more sense and with a buffered channel it's easier to implement.

**Review by jmoiron — COMMENTED** [review]
:+1:

**Pull request merged**
